sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk16
branches:
  only:
    - master
    
notifications:
  recipients:
    - a.gliznetsov@gmail.com
  email:
    on_success: always
    on_failure: always
cache:
  directories:
    - $HOME/.m2
